apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunter-backend-app-deployment
  namespace: hunter
  labels:
    app.kubernetes.io/name: hunter-backend-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hunter-backend-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hunter-backend-app
    spec:
      containers:
      - name: hunter-backend-app-container
        image: 779846792888.dkr.ecr.ap-south-1.amazonaws.com/dynamos-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: hunter
  name: hunter-backend-app-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: hunter-backend-app
